version: '3.7'

networks:
    nginx-php82-mysql8-node:


services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            -   "8080:80"
        volumes:
            - ./:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php82-service
            - mysql8-service
        networks:
            - nginx-php82-mysql8-node

    #php
    php82-service:
        build:
            context: .
            dockerfile: Docker/php/Dockerfile
        container_name: php82-container
        ports:
            -   "9000:9000"
        volumes:
            - ./:/var/www/project
        networks:
            - nginx-php82-mysql8-node

    #mysql
    mysql8-service:
        image: mysql:8
        container_name: mysql8-container
        ports:
            -   "3306:3306"
        volumes:
            -   ./mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret
            user: "1000"  # Set the user and group IDs
            group: "1000"
        networks:
            - nginx-php82-mysql8-node

    #node
    node-service:
        image: node:latest
        container_name: node-container
        volumes:
            - ./:/var/www/project
        working_dir: /var/www/project
        networks:
            - nginx-php82-mysql8-node

#services:
#    database:
#        image: 'mysql:latest'
#        environment:
#            MYSQL_ROOT_PASSWORD: password
#            MYSQL_DATABASE: main
#        ports:
#            # To allow the host machine to access the ports below, modify the lines below.
#            # For example, to allow the host to connect to port 3306 on the container, you would change
#            # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
#            # See https://docs.docker.com/compose/compose-file/compose-file-v3/#ports for more information.
#            - '3306'