controllers:
    prefix: /api
    resource:
        path: ../src/Controller/
        namespace: App\Controller

    type: attribute

login:
    path: /api/login_check

api_refresh_token:
    path: /api/token/refresh