controllers:
    prefix: /api
    resource:
        path: ../src/Controller/API/v1/
        namespace: App\Controller\API\v1

    type: attribute

login:
    path: /api/login_check

api_refresh_token:
    path: /api/token/refresh

api_token_invalidate:
    path: /api/v1/user/logout