name: Push-to-EC2

on:
  push:
    branches:
    - main


jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -p 22 -H 3.137.169.190  >> ~/.ssh/known_hosts

      - name: pull project
        uses: appleboy/ssh-action@master
        with:
          host: 3.137.169.190
          username: ubuntu #Jaanioo
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd var
            cd www
            cd ToDoList
            git fetch
            git reset --hard FETCH_HEAD
            git clean -d -f --exclude secrets
            git pull 
            docker compose up -d
            docker exec php82-container composer install
            docker exec -it mysql8-container bin/bash
            symfony console doctrine:migrations:migrate --no_interaction
