name: Symfony Example Action
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: intl, pdo_mysql
      - name: Install dependencies
        run: |
          composer install
      - name: Run tests
        run: |
          bin/phpunit